#!/bin/sh

current_ip=$(dig +short myip.opendns.com @208.67.222.222)
geo_loc_ip=$(geoiplookup  "$current_ip" | grep -Ev "(Country|IP Address not found)" | sed 's/^.*: //g')

command -v "notify-send" 1>/dev/null &&
	notify-send "   $current_ip" "$geo_loc_ip"
printf "ipv4: %s\n%s\n" "$current_ip" "$geo_loc_ip"
