#!/bin/sh
# https://sinanmohd.com

current_ip=$(dig +short myip.opendns.com @208.67.222.222)
geo_loc_ip=$(geoiplookup  "$current_ip" | grep -v "Country" | sed 's/^.*: //g')
notify-send "   $current_ip" "$geo_loc_ip"
