#!/bin/sh

url_yts="https://yts.mx"
menu="wmenu"

die()
{
	: "${1:?}"

	command -v notify-send > /dev/null &&
		notify-send "󰎁  yts" "$1"

	printf "\033[31;1merr: %b\033[0m\n" "$1"
	exit "${2:-1}"
}

dep_check()
{
	: "${1:?}"

	for dep; do
		command -v "$dep" 1>/dev/null ||
			die "$dep not found, please install it" 127
	done

	unset dep
}

get_yts()
{
	: "${1:?}"
	dep_check "curl"

	curl --silent -H 'Accept-Encoding: gzip,deflate, br' --compressed "${url_yts}/$1"
}

search_yts()
{
	: "${1:?}"

	get_yts "browse-movies/$(echo "$1" | sed 's/ /%20/g')/all/all/0/latest/0/all" |
		grep browse-movie-link | sed -e 's/^.*movies\///g' -e 's/".*$//g'
}

id_yts()
{
	: "${1:?}"
	fetch=
	select=

	fetch="$(get_yts "movies/$1" | grep -Eo "value=\"[A-Z0-9]{40}\">[a-zA-Z0-9 ]*")"
	select="$(echo "$fetch" | cut -d'>' -f2 | "$menu" -l 25 -p " ")"
	[ -n "$select" ] &&
		echo "$fetch" | grep "$select" | cut -d'"' -f2

	unset select
	unset fetch
}

main()
{
	query=
	fetch=
	id=
	out=

	[ -z "$WAYLAND_DISPLAY" ] &&
		menu="dmenu"
	if [ "$#" -gt 0 ] && [ "$1" = "-o" ]; then
		out=true
		shift
	fi

	dep_check "$menu"

	query="${*:-$(printf "" | "$menu" -p "󱇒 ")}"
	[ -z "$query" ] &&
		exit 1

	fetch="$(search_yts "$query")"

	id="$(id_yts "$(echo "$fetch" | tr '-' ' ' | "$menu" -l 25 -p "󰎁 " | tr ' ' '-')")"
	[ -z "$id" ] &&
		exit 1

	if [ "$out" = true ]; then
		echo "${url_yts}/torrent/download/${id}"
	else
		dep_check "pirowatch"
		pirowatch -s "${url_yts}/torrent/download/${id}"
	fi
}

main "$@"
